application: 
  port: 8000
<<<<<<< HEAD
  host: 0.0.0.0
  base_url: "http://0.0.0.0:8000"
database:
  host: "127.0.0.1"
=======
database:
  host: "localhost"
>>>>>>> master
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
<<<<<<< HEAD
  base_url: "http://localhost:8000"
=======
  base_url: "localhost"
>>>>>>> master
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000